### ISSUE TITLE
EPIC: DPIA verwerkingenlogging

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/verwerkingenlogging#158]
### 1. Epic omschrijving
Voor het verwerkingenloggging project moet een DPIA komen.

Heeft de VNG een DPIA?
- Nee

### 2. Gerelateerde issues
```[tasklist]
### Tasks
- [ ] https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/206
- [x] Laten lezen door Stijn
- [ ] https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/224
- [ ] https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/225
- [ ] https://github.com/GemeenteNijmegen/verwerkingenlogging/issues/242
- [x] Naar FG
```

**Comment by MartijnvDijk** [comment]
VNG heeft geen DPIA
