### ISSUE TITLE
Aanvraag API ontwikkelen

### ISSUE THREAD

**Issue by MartijnvDijk** [GemeenteNijmegen/verwerkingenlogging#481]
* Momenteel bestaat enkel de 'bewerking' api. Deze is bedoeld voor het inschieten van nieuwe verwerkingen. De aanvraag api is bedoeld voor applicaties als MijnNijmegen die de verwerkingen willen gaan tonen aan de burger.
* Deze api bestaat uit verschillende routes:
    * GET /verwerkte-objecten
    * GET /verwerkte-objecten/{verwerktObjectId}
* Dit betekent dus dat op basis van vewerkte-objecten gequeried kan worden. Verwerkte objecten zijn in de geval bijv. Personen. In een verwerkt object staat dat het gaat over een persoon met een bepaald BSN. Omdat een applicatie als MijnNijmegen beschikt over deze persoonsgegevens is het mogelijk om een verzoek te doen naar de Verwerkingenlogging en de alle gegevens op te halen gerelateerd aan een specifiek verwerkt object.
* Bij het aanvragen van gegevens gerelateerd aan een verwerkt object is het dus mogelijk om direct een verwerkt object ID mee te geven, of om een combinatie van gegevens mee te geven, namelijk:
    * ObjectType: Persoon
    * SoortObjectId: BSN
    * ObjectId: 123456789
    * BeginDatum: 01-01-2001
    * EindDatum: 01-01-2002
    * (Optioneel) VerwerkingsactiviteitId: uuid

Zie: https://vng-realisatie.github.io/gemma-verwerkingenlogging/api-read/aanvullendespecificatie-verwerkteobjecten-get.html

```[tasklist]
### Tasks
- [x] Route GET/verwerkte-objecten
- [x] Route GET/verwerte-objecten/{verwerktObjectId}
- [x] Gateway opzetten
- [ ] Aanvraag vanuit MijnNijmegen
```
